
baseURL = "https://enr.github.io/gip/"
languageCode = "en-us"
title = "gip"
theme = "gip"

[params]
  tagline = "Bulk Git operations across all your repositories."
  repoURL = "https://github.com/enr/gip"
  currentAppVersion = "0.6.0"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[taxonomies]
