= Gip
:author: {project-authors}
:revnumber: {project-version}
:source-highlighter: rouge

<<<


ifeval::["{backend}" == "html5"]

image::https://github.com/enr/gip/workflows/CI%20Linux%20Mac/badge.svg[CI Linux Mac]
image::https://github.com/enr/gip/workflows/CI%20Windows/badge.svg[CI Windows]

https://github.com/enr/gip/releases/latest[Download last artifacts] |
 https://enr.github.io/gip/pdf/gip_manual.pdf[Pdf manual] |
 Build revision `{ci-build-id}`
endif::[]

[[_book]]
## Usage

Gip manages your Git projects.

Gip reads a JSON or YAML file declaring all the repositories you want to manage.

[source,yaml]
----
- name: gip
  repository: "https://github.com/enr/gip.git"
  local_path: /tmp/gip
- name: nowhere
  repository: "https://nowhere.git"
  local_path: /nowhere/not/found
  pull_policy: never
----

[source,json]
----
[
  {
    "Name": "gip",
    "Repository": "https://github.com/enr/gip.git",
    "LocalPath": "~/Projects/gip"
  },
  {
    "Name": "...",
    "Repository": "...",
    "LocalPath": "..."
  }
]
----

You can set the path using the `-f` flag:

```
gip -f examples/linux.json -d pull -a
```

Otherwise it defaults to the file `.gip` in your home directory.

### Available commands

**ls**

List all managed projects

```
gip -f examples/linux.json -d ls
```

**pull**

Run git pull on managed projects.

The default behaviour is to pull only projects which `local_path` exists.

Projects with `pull_policy` set to `never` will be skipped, projects with `pull_policy` set to always will be pulled even if local path does not exist.

```
gip -f examples/linux.json -d pull
```

**status**

Run `git status` on all managed projects.

`statusfull` shows untracked files too.

```
gip -f examples/linux.json -d status
```

Get status hiding the warn about missing local directory:

```
gip -m sf
```

**other options**

Verbose output:

```
$ gip -d sf
```

Choose a path other than `~/.gip` for configuration file:

```
$ gip -f ~/.config/local/gip.json -d sf
```




## Install

The latest release is in: https://github.com/enr/gip/releases/latest

Put `gip` in your `$PATH` and make it executable:

```
$ curl -sL https://github.com/enr/gip/releases/download/v0.4.8/gip-0.4.8_linux_amd64.zip -o gip-0.4.8_linux_amd64.zip

$ unzip gip-0.4.8_linux_amd64.zip
Archive:  gip-0.4.8_linux_amd64.zip
   creating: gip-0.4.8_linux_amd64/
  inflating: gip-0.4.8_linux_amd64/gip

$ ./gip-0.4.8_linux_amd64/gip --version
gip version 0.4.8
Revision: 359819e2a81d7b5bc827af1adec84eb42632f706
Build date: 2020-02-05T22:30:46Z

$ ./gip-0.4.8_linux_amd64/gip --help
NAME:
   gip - Keep tracks of your Git projects

USAGE:
   gip [global options] command [command options] [arguments...]

VERSION:
   0.4.8
Revision: 359819e2a81d7b5bc827af1adec84eb42632f706
Build date: 2020-02-05T22:30:46Z

COMMANDS:
   status, s
   statusfull, sf
   list, ls
   pull
   help, h         Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --file value, -f value  path to the configuration file to use (if not set will be picked ${HOME}/.gip)
   --debug, -d             operates in debug mode: lot of output (default: false)
   --quiet, -q             operates in quiet mode (default: false)
   --ignore-missing, -m    ignores missing local directories, otherwise prints a warn (default: false)
   --help, -h              show help (default: false)
   --version, -v           print the version (default: false)
```


## License

Copyright (C) 2020 {project-authors}.
