name: CI Windows

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      run: |
        .sdlc/build.cmd
        .sdlc/check.cmd
