on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    container: 'golang:1.13'
    steps:
    - name: Prepare container
      run: |
        apt-get install git
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Create release
      run: |
        echo Release ${{ github.ref }}
